/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorysoftware.LogIn;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.StringTokenizer;
import java.util.Locale;

/**
 *
 * @author Geovani Prihanda
 */
public class ProductScreen extends javax.swing.JFrame {
    String pilihan = "" ;
    int harga_makanan;
    int jml_harga;
    int bayar, beli, Harga;
    

    /**
     * Creates new form ProductScreen
     */
    public ProductScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TeksHarga = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TeksBeli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TeksJumlahharga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TeksBayar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TeksKembalian = new javax.swing.JTextField();
        BtnKembalian = new javax.swing.JButton();
        BtnBatal = new javax.swing.JButton();
        BtnKeluar = new javax.swing.JButton();
        BtnHarga = new javax.swing.JButton();
        Combo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(910, 620));

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(169, 224, 49));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Toko Kelompok 9 Ok'e");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel2.setText("Nama Barang");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 140, -1));

        TeksHarga.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        TeksHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeksHargaActionPerformed(evt);
            }
        });
        jPanel1.add(TeksHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 220, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(169, 224, 49));
        jLabel3.setText("Jumlah Beli");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 140, -1));

        TeksBeli.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel1.add(TeksBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 220, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(169, 224, 49));
        jLabel4.setText("Jumlah Harga");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 140, -1));

        TeksJumlahharga.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        TeksJumlahharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeksJumlahhargaActionPerformed(evt);
            }
        });
        jPanel1.add(TeksJumlahharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 220, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(169, 224, 49));
        jLabel5.setText("Jumlah Bayar");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 140, -1));

        TeksBayar.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel1.add(TeksBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 220, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(169, 224, 49));
        jLabel6.setText("Jumlah Kembalian");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 200, -1));

        TeksKembalian.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel1.add(TeksKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 220, -1));

        BtnKembalian.setBackground(new java.awt.Color(169, 224, 49));
        BtnKembalian.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        BtnKembalian.setText("Jumlah Kembalian");
        BtnKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKembalianActionPerformed(evt);
            }
        });
        jPanel1.add(BtnKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));

        BtnBatal.setBackground(new java.awt.Color(169, 224, 49));
        BtnBatal.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        BtnBatal.setText("BATAL");
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));

        BtnKeluar.setBackground(new java.awt.Color(169, 224, 49));
        BtnKeluar.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        BtnKeluar.setText("Keluar");
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, -1, -1));

        BtnHarga.setBackground(new java.awt.Color(169, 224, 49));
        BtnHarga.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        BtnHarga.setText("Hitung Harga");
        BtnHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHargaActionPerformed(evt);
            }
        });
        jPanel1.add(BtnHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, -1, -1));

        Combo.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menu Pilihan", "Roti", "Es Krim", "Susu", "" }));
        Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboActionPerformed(evt);
            }
        });
        jPanel1.add(Combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 220, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(169, 224, 49));
        jLabel7.setText("Harga Barang");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 140, -1));

        jToggleButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jToggleButton1.setText("Para Kasir Toko");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 530, 140, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        // TODO add your handling code here:
        TeksBayar.setText("");
        TeksBeli.setText("");
        TeksHarga.setText("");
        TeksKembalian.setText("");
        TeksJumlahharga.setText("");
       

        
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKembalianActionPerformed
        // TODO add your handling code here:
         int kembali = Integer.parseInt(TeksBayar.getText());
         int total = kembali - bayar;
         
         TeksKembalian.setText("Rp. "+Integer.toString(bayar));
    }//GEN-LAST:event_BtnKembalianActionPerformed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHargaActionPerformed
        // TODO add your handling code here:
        Harga = Integer.parseInt(TeksHarga.getText());
        beli = Integer.parseInt(TeksBeli.getText());
        
        bayar = Harga * beli;
        
        DecimalFormat ankga = new DecimalFormat("###,###");
        TeksJumlahharga.setText(""+Integer.toString(bayar));
    }//GEN-LAST:event_BtnHargaActionPerformed

    private void ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboActionPerformed
        // TODO add your handling code here:
        pilihan = (String) Combo.getSelectedItem();
        switch (pilihan)
        {
            case "Roti":
                harga_makanan = 3000;
                break;
            case "Es Krim":
                harga_makanan = 5000;
                break;
            case "Susu":
                harga_makanan = 8000;
                break;    
                    
        }
        TeksHarga.setText(""+Integer.toString(harga_makanan));
    }//GEN-LAST:event_ComboActionPerformed

    private void TeksJumlahhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeksJumlahhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeksJumlahhargaActionPerformed

    private void TeksHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeksHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeksHargaActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBatal;
    private javax.swing.JButton BtnHarga;
    private javax.swing.JButton BtnKeluar;
    private javax.swing.JButton BtnKembalian;
    private javax.swing.JComboBox<String> Combo;
    private javax.swing.JTextField TeksBayar;
    private javax.swing.JTextField TeksBeli;
    private javax.swing.JTextField TeksHarga;
    private javax.swing.JTextField TeksJumlahharga;
    private javax.swing.JTextField TeksKembalian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
